version: '3.8'

services:
  playlist-updater:
    build: .
    container_name: iptv-playlist-updater
    restart: unless-stopped
    volumes:
      - ./output:app/output
      - ./repo:repo
    environment:
      OUTPUT_DIR: /app/output
      PYTHONUNBUFFERED: 1
      GIT_USER_NAME: "Docker Updater"
      GIT_USER_EMAIL: "updater@docker.local"
      GIT_TOKEN: ${GIT_TOKEN}
      GIT_REPO: "https://github.com/kadirsener1/vavoos.git"
    networks:
      - playlist-network

networks:
  playlist-network:
    driver: bridge
